#!/usr/bin/env python3
"""Regenerate shared/bracket-sources-snapshot.json from the frontend
bracketConfig.ts (v2.184.x).

The backend bracket-parity test reads the snapshot JSON inside the
container (via /app/shared/), since the frontend TS file isn't mounted
into the backend container directly. The snapshot is committed to git
so CI runs the parity check against a known-good record.

Workflow:
  1. Edit frontend/src/lib/config/bracketConfig.ts (the source of truth).
  2. Run this script from the repo root or backend dir:
       python backend/scripts/regen_bracket_parity_snapshot.py
  3. The snapshot at shared/bracket-sources-snapshot.json gets rewritten.
  4. Commit BOTH files together; CI verifies parity.

If you forget step 2-3, `test_bracket_parity.py` will fail loudly —
the snapshot will be stale relative to the TS file. That's by design.

Pure-stdlib parser; no Node toolchain required. Mirrors the regex
parser inside the test itself.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any


def _find_repo_root() -> Path:
    """Walk up from this script to find the repo root (has both
    `frontend/` and `backend/` siblings)."""
    here = Path(__file__).resolve()
    for ancestor in [here, *here.parents]:
        if (ancestor / "frontend").is_dir() and (ancestor / "backend").is_dir():
            return ancestor
    raise FileNotFoundError(f"Couldn't locate repo root walking up from {here}")


def _parse_ts_source(raw: str) -> dict[str, Any]:
    """Parse one TS source descriptor into the backend's normalised dict
    shape. Handles camelCase → snake_case (possibleGroups, matchNumber).
    """
    if "type: 'group'" in raw:
        m = re.search(r"position:\s*'([^']+)'", raw)
        if not m:
            raise ValueError(f"group source without position: {raw!r}")
        return {"type": "group", "position": m.group(1)}
    if "type: 'third_place'" in raw:
        m = re.search(r"possibleGroups:\s*\[([^\]]+)\]", raw)
        if not m:
            raise ValueError(f"third_place source without possibleGroups: {raw!r}")
        groups = [g.strip().strip("'") for g in m.group(1).split(",")]
        return {"type": "third_place", "possible_groups": groups}
    if "type: 'winner'" in raw:
        m = re.search(r"matchNumber:\s*(\d+)", raw)
        if not m:
            raise ValueError(f"winner source without matchNumber: {raw!r}")
        return {"type": "winner", "match_number": int(m.group(1))}
    if "type: 'loser'" in raw:
        m = re.search(r"matchNumber:\s*(\d+)", raw)
        if not m:
            raise ValueError(f"loser source without matchNumber: {raw!r}")
        return {"type": "loser", "match_number": int(m.group(1))}
    raise ValueError(f"Unknown source type in TS: {raw!r}")


_TS_MATCH_BLOCK = re.compile(
    r"matchNumber:\s*(\d+).*?"
    r"homeSource:\s*(\{[^}]+\}).*?"
    r"awaySource:\s*(\{[^}]+\})",
    re.DOTALL,
)


def main() -> int:
    repo = _find_repo_root()
    ts_path = repo / "frontend" / "src" / "lib" / "config" / "bracketConfig.ts"
    out_path = repo / "shared" / "bracket-sources-snapshot.json"

    if not ts_path.exists():
        print(f"ERROR: bracketConfig.ts not found at {ts_path}", file=sys.stderr)
        return 1

    text = ts_path.read_text(encoding="utf-8")
    sources: dict[str, dict[str, Any]] = {}
    for m in _TS_MATCH_BLOCK.finditer(text):
        match_num = int(m.group(1))
        key = str(match_num)
        if key in sources:
            print(f"ERROR: duplicate match number {match_num} in TS file", file=sys.stderr)
            return 1
        sources[key] = {
            "home": _parse_ts_source(m.group(2)),
            "away": _parse_ts_source(m.group(3)),
        }

    out_path.parent.mkdir(parents=True, exist_ok=True)
    # NOTE: Strict JSON — no // comments. The "_comment" field carries
    # the maintenance hint instead so consumers (humans + jq) see it.
    out_path.write_text(
        json.dumps(
            {
                "_comment": (
                    "AUTOGENERATED from frontend/src/lib/config/bracketConfig.ts. "
                    "Do not edit by hand. Regenerate via "
                    "`python backend/scripts/regen_bracket_parity_snapshot.py` "
                    "whenever the TS file changes. Consumed by "
                    "backend/tests/test_bracket_parity.py."
                ),
                "sources": sources,
            },
            indent=2,
            sort_keys=False,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(sources)} match definitions -> {out_path.relative_to(repo)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
