"""Add announcements table for the V4 Dashboard hero.

Revision ID: c5d6e7f8a9b0
Revises: b3c4d5e6f7a8
Create Date: 2026-06-11 12:00:00.000000

Admin-authored in-app news cards rotating in the dashboard hero banner
(v2.165.0). Hand-written (not autogenerated) following the audit_events
migration template — plain columns, no enums, no FKs (author_name is
denormalized on purpose so announcements survive admin renames without
a join).
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c5d6e7f8a9b0"
down_revision: Union[str, None] = "b3c4d5e6f7a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "announcements",
        sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
        sa.Column("tag", sa.String(length=32), nullable=False),
        sa.Column("tone", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("author_name", sa.String(length=80), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_announcements_published", "announcements", ["published"])
    op.create_index("ix_announcements_created_at", "announcements", ["created_at"])


def downgrade() -> None:
    op.drop_index("ix_announcements_created_at", table_name="announcements")
    op.drop_index("ix_announcements_published", table_name="announcements")
    op.drop_table("announcements")
